print("                                 Toko Mainan Anak                            ")
print("                       ####################################")
nama = str(input("masukan nama pembeli = "))
kode = str(input("masukan kode mainan = "))
harga = int(input("masukan harga = "))
jumlah = int(input("masukan jumlah mainan yang di beli = "))
total=jumlah*harga
print("=====================================================")
print("nama pembeli = ",nama)
print("kode mainan = ",kode)
print("harga = ",harga)
print("jumlah beli = ",jumlah)
print("total = ",total)
