def luas(sisi) :
    luas = sisi*sisi
    return luas
def  kel(sisi) :
    kel= 4*sisi
    print("keliling = ",kel)
print("="*50)
print("                 PROJECK AKHIR KELOMPOK 3 ")
print("                         10.1A.07         ")
print("Angota Kelompok : Qurrota Ayun H.P - ")
print("                  Gloria Wiradika Zai - ")
print("                  Rohim Kurniawan - 10200041")
print("Tema            : Aplikasi Pembelajaran Matematika Dasar")
print("                  Bangun Datar ")
print("="*50)
print("            APLIKASI PEMBELAJARAN MATEMATIKA DASAR BANGUN DATAR")
print("A. Pengertian Bagun Datar :")
print("Bangun Datar adalah  suatu bidang datar yang tersusun  oleh titik")
print("atau garis-garis yang menyatu membentuk bangun 2 Dimensi")
print("yang mempunyai keliling dan luas.")
print("B. Bangun datar kebagi menjadi 7 macam yaitu:")
print("1. Persegi")
print("2. Persegi Panjang")
print("3. Segitiga")
print("4. Jajar Genjang")
print("5. Belah ketupat")
print("6. Layang-Layang")
print("7. Trapesium")
print("8. Lingkaran")
print("Masukan nomer Bangun Datar yang ingin kalian baca dan pelajari")
bangun = int(input("Input Nomer > "))
print("-"*50)
print("*                                   *")
if bangun == 1 :
    print("1. Persegi")
    print("<a> Pengertian Persegi")
    print("Persegi adalah bangun datar 2 dimensi yang dibentuk oleh empat sisi yang sama panjang")
    print("dan keempat titik sudutnya membentuk sudut siku-siku (90º).")
    print("<b> Sifat sifat Persegi")
    print("Persegi atau kotak punya 4 sisi yaitu s yang semuanya sama panjang. Jadi, bisa dibilang")
    print("panjang AB = BC = CD = AD = s. Karena persegi memiliki 4 sudut siku-siku, maka ∠A = ∠B = ∠C = ∠D = 90°")
    print("dan total dari semua sudutnya adalah 360°. Ada juga diagonal yang berpotongan tegak lurus")
    print("dan saling membagi dua sama panjangPersegi memiliki 4 simetri lipat dan 4 simetri putar.")
    print("<c> Rumus rumus Persegi")
